spring.application.name=local_eoc
server.port=8081

spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

eoc.local.id=LOCAL-EOC-01
eoc.alerts.topic=disaster-alerts
