spring.application.name=database_writer
spring.main.web-application-type=none


# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.consumer.group-id=database_writer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=distsys26.database_writer.kafka.KafkaDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=*

eoc.alerts.topic=disaster-alerts


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/disaster_db
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect